<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoadPathFinder.Agents\RoadPathFinder.Agents.csproj" />
    <ProjectReference Include="..\RoadPathFinder.Models\RoadPathFinder.Models.csproj" />
  </ItemGroup>

</Project>
